name: image_clipper
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^0.1.2
  transparent_image: any
  flutter_staggered_grid_view: ^0.3.0
  
  # Util
  flutter_launcher_icons: any
  shared_preferences: ^0.5.4
  webview_flutter: ^0.3.16

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/

# flutter launcher icons
flutter_icons:
  image_path: "assets/icon/icon.png" 
  android: true
  ios: true